#DATASOURCE
spring.datasource: 
    continueOnError: true
    url: jdbc:oracle:thin:@(description=(address=(protocol=tcp)(host=10.253.129.65)(port=1521))(connect_data=(service_name=orcl)))
    username: dmp
    password: Clic1234
 
 
#测试环境发送邮件时，附件存放的根目录   
attachFileLocation: "D:\\"

#测试环境不发邮件
sendmailFlag: false

#测试环境不进行异常检测和异常消除
errorMonitorFlag: false